---
title: "Testy 2x2"
author: "pogRomcy danych"
date: "sezon 3 / odcinek 2<br><br> Wszelkie prawa zastrzeżone.<br> Wykorzystanie możliwe wyłącznie za zgodą autora.  <br><br><br><br>Naciśnij `A` by zamienić slajdy na ciągły tekst. <br> Naciśnij `T` by wyświetlić spis treści."
output:
  slidy_presentation:
    includes:
      in_header: ../tracking.html
    highlight: default
    css: ../style.css
    font_adjustment: 0
    footer: "pogRomcy danych / pierwsze kroki / testy 2x2"
---

# O czym jest ten odcinek

Nie tylko testy

* tabela kontyngencji

* jak ja narysowac (mosaic plot) i jak ja czytac

* testy

```{r}
library(PogromcyDanych)
library(dplyr)

plecCoWazne <- diagnoza %>% select(plec, gp29, waga_2013_osoby)
head(plecCoWazne)
```


```{r}
head(TCGA_BRCA)

```


---

# O czym jest ten odcinek

```{r}
table(plecCoWazne$plec, plecCoWazne$gp29)

prop.table(table(plecCoWazne$plec, plecCoWazne$gp29), 1)

fisher.test(table(plecCoWazne$plec, plecCoWazne$gp29))


prop.table(table(diagnoza$gp54_11, cut(diagnoza$wiek2013, c(0, 25, 40, 60, 110))), 2)

addmargins(table(ojcowiedziecmi = diagnoza$gp54_22, dziecirodzicami = diagnoza$gp54_11))

```

# tez 2xp

```{r}

prop.table(table(diagnoza$gp29, cut(diagnoza$wiek2013, c(0, 25, 40, 60, 110))), 2)

prop.table(table(diagnoza$gp29, diagnoza$eduk4_2013), 2)

prop.table(table(diagnoza$eduk4_2013, cut(diagnoza$wiek2013, c(0, 25, 40, 60, 110)), diagnoza$gp29), 1:2)

```

---

Test 2x2 McNemara

