---
title: "Dlaczego R?"
author: "pogRomcy danych"
date: "sezon 1 / odcinek 2<br><br> Wszelkie prawa zastrzeżone.<br> Wykorzystanie możliwe wyłącznie za zgodą autora.  <br><br><br><br>Naciśnij `A` by zamienić slajdy na ciągły tekst. <br> Naciśnij `T` by wyświetlić spis treści."
output:
  slidy_presentation:
    includes:
      in_header: ../tracking.html
    highlight: default
    css: ../style.css
    font_adjustment: 0
    footer: "pogRomcy danych / pierwsze kroki / dlaczego R"
---

# O czym jest ten odcinek

Zależność w diagnozie pomiędzy co jest wazne a grupa wiekowa

test chi2

```{r}

prop.table(table(diagnoza$gp29, cut(diagnoza$wiek2013, c(0, 25, 40, 60, 110))), 2)

prop.table(table(diagnoza$gp29, diagnoza$eduk4_2013), 2)

prop.table(table(diagnoza$eduk4_2013, cut(diagnoza$wiek2013, c(0, 25, 40, 60, 110)), diagnoza$gp29), 1:2)

```



```{r, eval=FALSE}
# brak przerzutow dobrze rokuje
table(TCGA_BRCA$new.tumor,
      TCGA_BRCA$vital.status)

fisher.test(table(TCGA_BRCA$new.tumor,
      TCGA_BRCA$vital.status))

fisher.test(table(TCGA_BRCA$new.tumor,
      TCGA_BRCA$TP53 == "Wild type"))


head(TCGA_BRCA)

table(TCGA_BRCA$TP53,
      TCGA_BRCA$vital.status)

chisq.test(table(TCGA_BRCA$TP53,
      TCGA_BRCA$vital.status))

pairwise.prop.test(TCGA_BRCA$new.tumor, TCGA_BRCA$TP53)

```


