---
title: "Sample, population, estimation, testing"
author: "Data CruncheRs"
date: "season 2 / episode 11 <br><br><br><br>Press `A` to turn slides into full text  <br> Press `T` to show Table of Contents"
output:
  slidy_presentation:
    includes:
      in_header: ../tracking.html
    highlight: default
    css: ../style.css
    font_adjustment: 0
    footer: "Data CruncheRs / modelowanie / wstęp do modelowania"

---

# What is this episode about

Upcoming episodes will present a few selected techniques for the analysis of quantitative and qualitative data.

Those techniques will be shown on a number of levels. It's worth it to be aware of them to get to know them better.

1. Utility level. For each method, we'll show you one or two examples of how to perform a specific analysis in R program, and how to interpret the results.

2. Conceptual level. For each method, we'll show how the presented algorithms work, how the algorithm producing these results looks like.

3. Issue level. For each method, we'll show how the presented algorithms are related to the issue that we want to solve.

In order to efficiently represent the selected data analysis algorithms, we refer to the first of several terms/concepts crucial to statistical analysis of the data.

# Key concepts - dependence

One of the terms used during data analysis is dependence. Most frequently it concerns the dependence between the two characteristics.

When are we dealing with the dependence between the variables? If for different values of one variable we observe values of the other variable at different frequencies.

For example, for adults there exists a dependence between growth and gender.

That dependence is symmetrical, therefore:

- Males are on average taller than females, i.e. when we observe a male, larger height values are more often associated with him.
- Taller persons are often males, i.e. when we observe a tall person, it is more often a male.

Let's note that:

1. Dependence is associated with a trend but does not constitute 100% functional compound. In essence, it does not mean that all persons below a specific height are *always* females. You may encounter very tall females and very short males, but it does not contradict the general regularities that on average, males are taller.
2. Dependence is visible for the entire population, but need not be true for subgroups. If we compared two groups of females and males, and it so happened that one of these groups would be female volleyball players (tall females) and the second group would be male jockeys (usually short males) the dependence visible for the entire population would not be present in such groups. Thus, when we observe subgroups, a dependence true for the entire population is not always apparent in these subgroups.
3. Dependence may involve two quantitative variables (e.g. weight and height, taller people are usually heavier) and qualitative (e.g. hair color and eye color).
4. Strength of the dependence between variables is graded. Two variables can be very weakly dependent or heavily dependent.


# Key concepts - randomness

Although we are accustomed to thinking about the values as certain fixed numbers, it is not always possible.

For example, is it possible to tell what is the average height of males in Poland?

If we randomly chose 1000 males we could gather their height and calculate a mean value. However, if we chose different 1000 persons, we may get a different mean value. Thus, on the basis of trial we can conclude something about the average height but such a conclusion is burdened with a certain randomness resulting from the random selection of those 1000 persons.

But what if we had measured all Poles? Would we then get one constant value every time? Not necessarily. In the morning we are taller than in the evening. Average height is thus dependent on the time of measurement. If we pick the time of the measurement randomly we can get different mean values even for the same persons.

But what if we had measured all Poles at exactly 10 in the morning? Would we then get one constant value? Also not, there is no such thing as a universal set of all Poles. At night, someone dies, someone is born, proportions change, perhaps slightly, nevertheless always, between the number of children and adults, and so the set of all Poles is constantly changing, thus prompting changes to their average height.

Obviously such changes are not large, yet they show that not every value can be measured with 100% accuracy. Some values, such as the average height, are constantly fluctuating and we should keep such fluctuations in mind.


# Key concepts - measurement accuracy

Some characteristics, such as height, are immeasurable because the whole concept of average height has such a nature. 

However, there are also features that (we believe) have a certain value, yet they can only be evaluated with certain accuracy.

For example, if you weigh in on a scale, we have a certain weight when we step on the scale. However, subject to different factors such as temperature, efficiency of the scale, we can get different results. Standard scales have accuracy of +/- 2 kg, so the same person can get slightly different measurements on different scales.

Measurement accuracy also applies to a situation in which the measurement is not made with a mechanical device, but e.g. a survey or a poll, as in the case of measuring political preferences. In this case, the measurement error results from the inability to carry out a survey on all Poles, and the need to conduct a survey on typically small sized sample group.


# key concepts - sample and population

Typically, we use data analysis tools to gather a certain general regularity. A universal rule.

When we analyze the effectiveness of a medication on 100 patients, we do not do it in order to assess whether these particular 100 patients respond to the therapy, but to transfer the conclusions on larger population. We want to know whether the medication is effective.

Thus, we want to transfer the generalized conclusions obtained from the sample group onto the entire population. On the other hand, we are aware of randomness arising from the sample, which may not always reflect the dependence present in the entire population.

In the data analysis a lot of attention is paid to determining how accurate are the results, and to what extent their accuracy depends on the size and representativeness of the sample.

# Key concepts - estimation and testing

In the classic data analysis, the data is often divided by two types of algorithms, estimation and testing.

Estimation is an activity designed to estimate on the basis of a sample the value of the parameters in the population. For example,

* based on 1000 respondents we want to evaluate what is the support for party X.
* based on a batch of 100 shoes we want to evaluate their abrasion resistance.
* based on 1000 cars we want to evaluate their reliability.

The result is an estimate of the specified values and information about how accurate this estimate is.


Testing is an action aimed at determining whether a certain value in the population meets a specified condition. For example

* we can test whether the support for the party X is greater than that for the party Y
* we can test whether the average resistance of the shoes allows them to be used for 2 seasons
* we can test whether 80% of the cars won't break down within the next 5 years.


In subsequent episodes we'll present various issues of data analysis, and we will show the methods used for estimation/assessment of the specific value and for testing specific conditions for this value.

# Table of contents

Modeling materials are divided into following episodes

Introduction to data exploration

+ data exploration

Two episodes on trend analysis

+ quantitative variables - trend analysis
+ quantitative variables - trend testing

Episode on mean values analysis

+ quantitative variables - comparison of two groups

Two episodes on linear, interval and multiplicative regression

+ quantitative variables - linear regression
+ quantitative variables - interval and linear regression

Two episodes on qualitative variables

+ qualitative variables - 2x2 tables
+ qualitative variables - contingency tables

