# 0 = echo=FALSE, results="hide", eval=FALSE
use_code=1
knitr_error=FALSE

files:= 11_intro 12_eksploracja 13_trendLiniowy 14_trendLiniowyTest 15_testSrednie 16_regresjaProsta 17_regresjaMultiplikatywna 18_test2x2 19_test2xp 20_coDalej

include ../Makefile
