---
title: "Wizualizacja / wprowadzenie do ggplot2"
output:
  html_document:
    toc: yes
---

# Zaawansowany do pakietu ggplot2

## Wykres paskowy

```{r, warning=FALSE}

library(SmarterPoland)
ggplot(skiJumps2013, aes(x=jumperCountry)) + geom_bar()

skiJumps2013$jumperCountry <- reorder(skiJumps2013$jumperCountry, 
                                      skiJumps2013$jumperCountry, 
                                      length)
ggplot(skiJumps2013, aes(x=jumperCountry)) + geom_bar()

ggplot(skiJumps2013, aes(x=jumperCountry)) + geom_bar() + coord_flip()

```


## Wykres punktowy

```{r, warning=FALSE}

skiJumps2013 %>%
  group_by(jumperCountry) %>%
  summarise(suma = sum(classPoints, na.rm=TRUE))

sj <- skiJumps2013 %>%
  group_by(jumperSurname, jumperName, jumperCountry) %>%
  summarise(suma = sum(classPoints, na.rm=TRUE))

as.data.frame(sj) %>%
  arrange(suma)


ggplot(skiJumps2013, aes(x=jumperCountry)) + geom_bar()

skiJumps2013$jumperCountry <- reorder(skiJumps2013$jumperCountry, 
                                      skiJumps2013$jumperCountry, 
                                      length)
ggplot(skiJumps2013, aes(x=jumperCountry)) + geom_bar()

ggplot(skiJumps2013, aes(x=jumperCountry)) + geom_bar() + coord_flip()

```

## Wykres z etykietami


## Wykres trendu







