---
title: "Dlaczego R?"
author: "pogRomcy danych"
date: "sezon 1 / odcinek 1 <br><br><br><br>Naciśnij `A` by zamienić slajdy na ciągły tekst. <br> Naciśnij `T` by wyświetlić spis treści."
output:
  slidy_presentation:
    includes:
      in_header: ../tracking.html
    highlight: default
    css: ../style.css
    font_adjustment: 0
    footer: "pogRomcy danych / pierwsze kroki / dlaczego R"
---

# O czym jest ten odcinek

Jest wiele powodów, dla których warto poznać język R do analizy danych.

Być może jesteś zaawansowanym w boju badaczem danych z doskonałą znajmomością SPSS / SAS / Statistica czy Stata.

Być może jesteś analitykiem biznesowym z niezłą znajomością Excela lub Tableau.

Być może Twóje dotychczasowe doświadczenia to programowanie w językach takich jak Python, Java czy C++.

Być może masz za sobą pierwsze przymiarki do R czy to na zajęciach czy w ramach dokształcania się.

A może jeszcze nie trafiłeś na rynek pracy i z czysto poznawczej ciekawości zajrzałeś na stronę tego kursu.

Tak czy inaczej aby analizować dane potrzebujesz dobrego narzędzia i umiejętności pracy z danymi. 
Ten odcinek ma na celu zachęcenie Cię do dokładniejszego poznania języka R.

Pokażemy dlaczego warto poznać R, co można w tym języku zrobić oraz powiemy jak sie tego języka nauczyć. 
Powiemy też jakie umiejętności są potrzebne by efektywnie pracować z danymi w tym czy innym narzędziu oraz powiemy jak te umiejętności nabyć.

---

# Dlaczego R?

*R jest dojrzałym językiem programowania zaprojektowanym z myślą o analizie danych oraz wizualizacji danych dostępnym bezpłatnie na otwartej licencji GPL.*

Przyjrzyjmy się temu zdaniu dokładniej.

*R jest językiem programowania.* Oznacza to, że nie jest ograniczony do kilku algorytmów, które przewidzieli twórcy, ale każdy może napisać w nim własny algorytm Co więcej wiele osób korzysta z tej opcji i tworzy nowe algorytmy które inni użytkownicy R mogą wykorzystywać. Dzięki temu liczba algorytmów i funkcji dostępnych w R bardzo szybko sie zwiększa.

*Jest dojrzałym jezykiem.* Jest rozwijany od ponad 21 lat, co oznacza, dzięki cezmu zdążył nabrać masy krytycznej. Pewne usterki projektowe wczesnych wersji R (ograniczenie do 4GB RAM) zostały dostrzerzone i wyeliminowane. Dziś jest to narzędzie rozwijane i przez dużą grupę statystyków i inżynierów oprogramowania, co jest gwarancją stabilnego rozwoju.

*Zaprojektowanym z myślą o analizie danych.* Dojrzałych języków programowania jest wiele, ale niewiele z nich nadaje się do interaktywnej pracy z danymi. W języku R połączono wybrane cechy języków funkcyjnych oraz obiektowych, nacisk położono na pracę interaktywną z danymi. Dodatkowe biblioteki wspierają łatwe tworzenie raportów z wynikami. Dzięki tym cechom R jest stworzony do analizy danych.

*Wizualizacji danych.* W języku R można wykonać grafiki statystyczne o publikacyjnej jakości. Oznacza to, że bez dodatkowych narzędzi można stworzyć profesjonalny wykres. Co więcej, jest wiele pakietów, dzięki czemy tworzenie takich wykresów jest proste. Omówiy je w drugim sezonie tego kursu.

*Dostępny bezpłatnie na otwartej licencji GPL.* Program R jest dostępny bezpłatnie do każdych zastosowań. Czy to na uczelni, czy w działalności komercyjnej, możemy go wykorzystywać bez żadnych opłat. Co więcej, jest otwarty na otwartej licencji, co oznacza, że każdy ma dostęp do źródeł, każdy element można zobaczyć jak funkcjonuje, można sprawdzić czy nei zawiera błędów i ewentualnie usprawnić. 

---

# Dlaczego R?

Dzięki tym cec
R is a programming language designed for statistical computing and visualization. For many years, R has been a language of choice for academic researchers, but in recent years, it has grown in popularity in business. It can now be found across industries (financial services, technology, retail, etc.) and job functions (marketing, operations, finance, etc.).

According to Google Trends, interest in R has more than doubled, while interest in both SAS and SPSS has been cut in half over the past ten years. This could mean more jobs and opportunities for those who know R.






W jaki sposób analizuje się dane?
Kiedyś analiza wykonywana była ołówkiem na papierze.
Spisywało się kolumnę liczb, dodawało, dzieliło, mnożyło.

Teraz do analizy danych wykorzystywane są komputery.
Dostępnych jest bardzo wiele programów pozwalających na analizę danych,
Różnią się one ceną, łatwością użycia, automatyzacją pracy.

Wybierzemy jedno narzędzie, najlepsze do naszych celów.
Szukając najlepszego narzędzia, zastanówmy się nad kilkoma kwestiami.


Czy potrafisz podac argument za każdym z tych wyborów?

1. Klikamy czy piszemy skrypty?

Klikamy: Narzędzia pozwalające wyklikać wyniki lub analizę są bardziej odporne na literówki. Jeżeli mamy więc problem z obsługą klawiatury, to klikane narzędzia mają zaletę.

Klikamy: Jeżeli klikane narzędzie ma dobry interface, to widzimy wszystkie opcje, które mamy do wyboru. Gdy piszemy skrypty, najczęściej musimy pamiętać jakie komendy można wykorzystać.

Piszemy skrypty: Jeżeli raz opracujemy skrypt wykonujący pewną pracę, możemy następnie ją łatwo powtórzyć. Wystarczy cały skrypt skopiować. Dzięki temu w miarę nabywania doświadczenia zwiększamy nasz potencjał.

Piszemy skrypty: Jeżeli otrzymujemy dziwne wyniki, to całą ścieżkę analizy, któ®a prowadzi do tych wyników możęmy przeanalizować. Jest ona zapisana krok po kroku jako skrypt. Nie musimy jej przywoływać z pamięci.

Co wybieramy?


2. Narzędzie dedykowane do konkrentego celu, czy narzędzie ogólengo rażenia.

Dedykowane: Dedykowane specjalistyczne narzędzia mogą posiadać odpowiedni interface pozwalający na szybkie wykonanie określonych operacji

Ogólnego rażenia: Jeżeli 



4. Zamknięte czy otwarte oprogramowanie?

Zamknięte oprogramowanie jest często własnością firmy, która je wytworzyła. 
Firmy takie często oferują pomoc w przypadku wystąpienia problemów.

Otwarte oprogramowanie, o ile osiągnie określoną masę krytyczną, rozwijane jest przez wiele osób.


Bonus: Ile kosztuje narzędzie, które wybierzemy?
Jest bezpłatne do wszelki zastosowań.



Wybieramy R





- data handling
- statistical / numerical analysis / modeling
- data visualisation
- reproducible research

,,stworzony do eksploracji danych''
,,pełna otwartość - wygodne w audytach ''
,,duża baza uzytkowników i developerów''
używany przez Googla, Facebooka, NY Times, New Scientist, 
HPC




Cytaty wiodące:

R is really important to the point that it’s hard to overvalue it. It allows statisticians to do very intricate and complicated analyses without knowing the blood and guts of computing systems. Google research scientist, quoted in the New York Times

The great beauty of R is that you can modify it to do all sorts of things, and you have a lot of prepackaged stuff that’s already available, so you’re standing on the shoulders of giants. Google chief economist, quoted in the New York Times

Frank Harrell 
one of the greatest advantages of R: getting your work done better and in less time.
Frank Harrell
Chairman, Biostatistics, Vanderbilt University


“R has really become the second language for people coming out of grad school now, and there’s an amazing amount of code being written for it,” said Max Kuhn, associate director of nonclinical statistics at Pfizer.


It’s a mature, widely used (around 1-2 million users) and well-supported free and open source software project; it’s committed to an annual schedule for major updates (it runs on GNU/linux, unix, MacOS and Windows)

Excellent graphics capabilities (see also here)

Vector arithmetic, plus many built-in basic & advanced statistical and numerical analysis tools

Intelligent handling of missing data values (denoted by NA)

Highly extensible, with over 4300 user-contributed packages available

It’s easy to use and has excellent online help and associated documentation




