---
title: "Intro dla kursu ,,pogRomcy danych''"
author: "pogRomcy danych"
date: "sezon 1 / odcinek 1 <br><br> Wszelkie prawa zastrzeżone.<br> Wykorzystanie możliwe wyłącznie za zgodą autora. <br><br><br><br>Naciśnij `A` by zamienić slajdy na ciągły tekst. <br> Naciśnij `T` by wyświetlić spis treści."
output:
  slidy_presentation:
    includes:
      in_header: ../tracking.html
    highlight: default
    css: ../style.css
    font_adjustment: 0
    footer: "pogRomcy danych / pierwsze kroki / intro"
---

# Co to za kurs?

*PogRomcy danych* to zbiór dwóch kursów o przetwarzaniu, wizualizacji i modelowaniu danych.

Kursy zostały przygotowane dla osób, które pracują, chciałyby pracować, lub są ciekawe jak wygląda, praca z danymi. Oba kursy są prowadzone na poziomie podstawowym. Zakładamy jedynie ogólną orientację jak wygląda tabela z danymi w arkuszach kalkulacyjnych, np. takich jak Excel, oraz ogólną umiejętność pracy z komputerem. 

Wcześniejsza znajomość programowania będzie bardzo przydatna, ale nie jest konieczna. Wszystkie nowe pojęcia pokazujemy na przykładach związanych z analizą ciekawych danych.

W pierwszym kursie pokażemy jak pracować z programem R, bezpłatnym i bardzo potężnym narzędziem do analizy danych. Pokażemy jak pisać programy, tworzyć funkcje, pętle, wczytywać, przetwarzać i zapisywać dane.

W drugim kursie pokażemy co wyróżnia zły, a co dobry wykres. Następnie pokażemy jak tworzyć dobre wykresy korzystając z programu R. Druga część dotyczy modeli i metod statystycznych. Pokażemy jak badać zależności pomiędzy dwoma lub większą liczbą zmiennych.

Oba kursy zwieńczone są zbiorem 20 zadań do samodzielnego wykonania. Osoby, które wykonają 13 lub więcej zadań otrzymają tytuł ,,Pogromców danych’’ oraz certyfikat ukończenia kursu sygnowany przez Uniwersytet Warszawski. 

Aby uzyskać dostęp do materiałów potrzebna jest rejestracja. Jest ona bezpłatna i otwarta dla każdego zainteresowanego. Zarejestrowani uzyskują dostęp do materiałów dydaktycznych, forum oraz zadań. 
Materiały dydaktyczne zostały podzielone na krótkie bloki, omawiające kolejne zagadnienia. Każdy blok kończy się krótkimi sprawdzającymi zadaniami. W materiałach znajdują się również przykładowe odpowiedzi do tych zadań.

Do obu kursów dostępne jest forum, ułatwiające komunikacje pomiędzy uczestnikami. Jeżeli jakaś porcja materiału jest trudna, sprawia kłopoty, lub jeżeli w trakcie pracy pojawią się ciekawe rozwiązania, warto podzielić się nimi na forum. Obsługa kursu śledzi forum i odpowiada na wszelkie, nawet najbardziej podstawowe pytania. Również inni uczestnicy kursu mogą coś zasugerować lub pomóc w rozwiązaniu problemu.

---

# Pierwszy sezon jest o programie R

Pierwszy kurs, jest poświęcony programowi R. Rozpoczyna się od czterech odcinków pokazujących dlaczego warto nauczyć się tego programu, jak go zainstalować, jak doinstalować wygodny edytor oraz dodatkowe pakiety do pracy z R. Następnie omawiane są podstawy pracy z programem R. Pokażemy jak i gdzie wpisywać komendy oraz gdzie spodziewać się wyników.

Kolejne trzy odcinki poświęcone są wczytywaniu i zapisywaniu tabel z danymi, oraz podstawowym operacjom na tych tabelach z danymi. Pokażemy jak wczytać plik tekstowy lub w formacie Excela do programu R. Jak zapisać wyniki oraz jak z wyników wybrać tylko określone kolumny lub wiersze.

Odcinki 8, 9, 10 pokazują jak automatyzować obliczenia. Wyjaśniamy w nich na przykładach jak działają pętle, instrukcje warunkowe oraz jak tworzyć własne funkcje.

Odcinki od 11 do 15 wprowadzają funkcje i operacje typowe dla najpopularniejszych rodzajów. Pokażemy co można zrobić z wektorem liczb, a co z wektorem napisów lub dat. Wyjaśnimy czym są zmienne logiczne i jakościowe oraz jakie operacje na nich można wykonać.

Odcinki od 16 do 24 przedstawiają szeroki wachlarz funkcji pozwalających na swobodne przekształcanie danych. Opanowawszy te funkcje będziemy potrafili wykonać 90% typowych prac związanych z przetwarzaniem danych. Będziemy wiedzieć jak filtrować, przekształcać, agregować, grupować dane i zmieniać ich strukturę.

Ten kurs jest kursem podstawowym, ale kończy go odcinek pokazujący gdzie można szukać dalszych informacji o programie R. Jeżeli program R przypadnie nam do gustu, w ostatnim odcinku pokażemy jak go dalej zgłębiać.

---

# Drugi sezon jest o wizualizacji i modelowaniu

Pierwszy kurs pokazuje jak przetwarzać dane, drugi kurs pokazuje po co to robić. W tej części przedstawimy zagadnienia związane z eksploracją danych, wizualizacją oraz modelowaniem statystycznym.

Rozpoczynamy od trzech odcinków pokazujących kamienie milowe w historii wizualizacji danych, trudności związane z prezentowaniem danych, problemy wynikające ze sposobu w jaki nasz mózg interpretuje obraz a następnie pokażemy przykłady rzetelnych oraz nierzetelnych wykresów.

Odcinki 4, 5, 6 i 7 wprowadzą nas w świat pakietu ggplot2. Poznamy podstawowe i bardziej zaawansowane instrukcje, pozwalające na wykonanie praktycznie dowolnego wykresu w programie R.
Jeżeli praca z wykresami w programie R nas zaciekawi, to w odcinku 8 przedstawimy sugestie dalszych materiałów rozwijających nasze umiejętności wizualizacji danych.

Kolejne odcinki przedstawią podstawowe narzędzia statystyczne służące do eksploracji danych do analizy statystycznej danych. Pokażemy jak statystycznie porównać dwie średnie. Jak sprawdzić czy dwa zjawiska występują niezależnie czy też czy jest pomiędzy nimi jakaś zależność. Oraz pokażemy jak tworzyć modele regresyjne np. aby prognozować pewną cechę w przyszłości.
Również ten blok zakończy się listą propozycji literaturowych w których można znaleźć więcej informacji na temat modelowania statystycznego.

Do obu kursów dodaliśmy przykłady bardzo ciekawych ale i nietypowych zastosowań analizy danych. Pokażemy jak analiza danych jest wykorzystywana w analizie danych sondażowych, robotyce, inżynierii lingwistycznej i meteorologii.

---

# Stromej krzywej uczenia nie należy się obawiać

Analiza danych, a w szczególności analiza z użyciem programu R, charakteryzuje się stromą krzywą uczenia. Na początku wiele rzeczy będzie nowych i trudnych. Przygotowaliśmy jednak wiele materiałów i na bieżąco monitorujemy forum, aby odpowiadać na wszelkie pytania i pomagać w stawianiu pierwszych kroków. Gwarantujemy jednak, że wysiłek włożony w poznawanie programu R opłaci się. Lepiej będziemy mogli zrozumieć co właściwie robimy w analizach. Z czasem będziemy coraz sprawniej przetwarzać dane, a elastyczność i ekspresja programu R powodują, że praktycznie nie będzie przed nami barier związanych z analizą najróżniejszych danych. 

Pracując ze slajdami, możemy w każdej chwili nacisnąć przycisk `T`, rozwinie on spis treści lub przycisk `A`, aby zamienić slajdy na ciągły dokument.

