---
title: "Jak zapisać dane z programu R"
author: "pogRomcy danych"
date: "sezon 1 / odcinek 6 <br><br><br><br>Naciśnij `A` by zamienić slajdy na ciągły tekst. <br> Naciśnij `T` by wyświetlić spis treści."
output:
  slidy_presentation:
    includes:
      in_header: ../tracking.html
    highlight: default
    css: ../style.css
    font_adjustment: 0
    footer: "pogRomcy danych / eksploracja danych / zapisywanie danych z R"
---

# O czym jest ten odcinek

Program R jest świetnym narzędziem do przetwarzania danych. Mając już dane przetworzone pojawia się potrzeba by wyniki gdzieś zapisać.

Podobnie jak wczytywaliśmy dane z formatów tekstowych, binarnych lub plików Excela, również możemy zapisywać dane do różnych formatów.

W tym odcinku dowiemy się

- Jak zapisać dane tabelaryczne do plików tekstowych?
- Jak zapisać dane tabelaryczne do plików Excela [xls lub xlsx]?
- Jak zapisać dane w postaci binarnej?
- Gdzie szukać informacji o tym jak wczytać dane z innych źródeł?

---

# Zapisywanie danych tabelarycznych do plików tekstowych

Dane, które są dostępne w programie R, można zapisać do pliku tekstowego, funkcją `write.table()`. Formatowanie określa się w ten sam sposób co w funkcji `read.table()`.

Deklaracja funkcji `write.table()` jest następująca

```{}
write.table(x, file = "", append = FALSE, quote = TRUE, sep = " ",
            eol = "\n", na = "NA", dec = ".", row.names = TRUE,
            col.names = TRUE, qmethod = c("escape", "double"),
            fileEncoding = "")
```

Najczęściej wykorzystywane argumenty to 
- `x` - określa jaka tabela ma być zaisana do pliku tekstowego,
- `file` - określa nazwę pliku tekstowego, do którego dane będą zapisane,
- `append` - domyślna wartość `FALSE` oznacza, że plik o nazwie `file` istnieje wcześniej to zostanie on skasowany. Jeżeli ustawić `append=TRUE` to nowe dane będą dopisane do końca poprzedniego pliku.
- `sep` - określa znak, który jest separatorem kolejnych wartości,
- `dec` - określa znak, który jest kropką dziesiętną, zazwyczaj `.` lub `,`
- `row.names` - określa czy do pliku tekstowego mają być zapisywane nazwy wierszy, domyślnie `TRUE`
- `col.names`  - określa czy do pliku tekstowego mają być zapisywane nazwy kolumn, domyślnie `TRUE`

---

# Zapisywanie danych tabelarycznych do plików w formacie Excela

Dane, które są dostępne w programie R, można zapisać pliku excelowego funkcją `write.xls()`. Funkcja ta jest dostępna w większości pakietów, zawierających funkcję `read.xls()`, np. w pakiecie `xlsx` (korzysta z biblioteki Java) oraz `dataframe2xls` (korzysta z zewnętrznych bibliotek Pythona).

Do zapisu do formatu Excela można też wykorzystać funkcję `WriteXLS()` z pakietu `WriteXLS` (korzysta z zewnętrznych bibliotek Perla).

Podstawowa funkcjonalność tych funkcji jest taka sama, pozwalają one na stworzenie nowego pliku oraz zapisania do niego tabeli.

Funkcje te różnią się dodatkowymi funkcjami. Niektóre potrafią zapisywać do plików Excelowych, które mają wiele zakładek. Inne potrafią zapisywać do pliku Excela z dodanym formatowaniem, takim jak określone kolory, wielkość pisma, krój czcionki, obrysowania tabeli.

Najczęściej korzystam z pakietu `xlsx`, ponieważ pozwala on na zapis danych do wielu zakładek z zadanym formatowaniem. 

---

# Zapisywanie danych do plików binarnych

Dane, które są dostępne w programie R, można zapisać do pliku tekstowego, pliku excelowego lub binarnego funkcjami:

Do pliku w formacie natywnym R, dane można zapisać funkcją `save()`. Funkcja ta zapisuje jeden lub więcej zmiennych o dowolnych formatach. Nie tylko tabelarycznych. 

Wadą tego rozwiązania jest to, że format ten nie jest odczytywany rzez inne pakiety statystyczne. 

Jeżeli jednak pracujemy głównie z programem R i chcemy w przyszłości te dane odczytywać tylko z programu R, to jest to najwygodniejsza opcja.


---

# Zadanie

- Zapisz zbiór danych `koty_ptaki` do pliku tekstowego, w którym dane są rozdzielane przecinkiem a kropką dziesiętną jest `.`
- Zapisz zbiór danych `koty_ptaki` do formatu pliku Excela. Sprawdź czy dane poprawnie się zapisały.
- Zapisz zbiór danych `koty_ptaki` do pliku binarnego. Odczytaj go następnie funkcją `load()` i sprawdź czy dane poprawnie zostały zapisane.

---

# Więcej informacji 

Gdzie szukać dalej

- Więcej informacji o tym jak wczytywać dane z innych formatów oraz baz danych znaleźć można w rozdziale 2.2 książki *,,Przewodnik po pakiecie R''*. Rozdział ten jest dostępny bezpłatnie pod adresem http://biecek.pl/R.

- Bardziej szczegółowe informacje o tym jak wczytywać i zapisywać dane z i do baz danych lub plików w egzotycznych formatach znaleźć można w dokumencie *,,R Data Import/Export''*
http://cran.r-project.org/doc/manuals/r-release/R-data.pdf
https://github.com/pbiecek/MOOC/blob/master/materialyZewnetrzne/R-data.pdf?raw=true

- O ile *,,R Data Import/Export''* jest opisem ,,teoretycznym'' to bardzo ciekawe zebranie przypadków użycia funkcji do wczytywania danych z różnych formatów jest zebrane w wiki-książce *,,R programming''* dostępnej pod adresem 
http://en.wikibooks.org/wiki/R_Programming/Importing_and_exporting_data

- Interesujące zestawienie narzędzi do odczytywania danych ze stron interentowych znaleźć można na stronach z materiałami dydaktycznymi Gastona Sancheza
http://gastonsanchez.com/teaching/


