---
title: "Frequently asked questions (FAQ)"
author: "pogRomcy danych"
date: "sezon 1 / odcinek FAQ <br><br><br>Naciśnij `A` by zamienić slajdy na ciągły tekst. <br> Naciśnij `T` by wyświetlić spis treści."
output:
  slidy_presentation:
    includes:
      in_header: ../tracking.html
    highlight: default
    css: ../style.css
    font_adjustment: 0
    footer: "pogRomcy danych / faq"

---

<b>Pytanie:</b> 

Ile razy można zgłaszać rozwiązania i w jakiej kolejności?

<b>Odpowiedź:</b>

Rozwiązania zadań z 'Challenge' można zgłaszać w dowolnej kolejności. Do każdego zadania można podchodzić wielokrotnie i nie ma żadnych konsekwencji zgłaszania złych rozwiązań.

Aby zaliczyć kurs należy rozwiązać 15 z 20 zadań, bez znaczenia których. W przypadku pierwszego kursu, liczą się tylko rozwiązania przesłane do 29 kwietnia.

<b>Pytanie:</b> 

Czy otrzymam wydrukowany dyplom czy pdf?

<b>Odpowiedź:</b> 

Dyplomy będą rozsyłane po zakończeniu kursu za pomocą poczty elektronicznej.

<b>Pytanie:</b> 

Czy materiały będą dostępne po zakończeniu kursu?

<b>Odpowiedź:</b>

Tak, będą dostępne, choć jeszcze nie jest ustalone w jakiej formule.

<b>Pytanie:</b> 

Czy mogę brać udział w kursie, jeżeli późno się zarejestowałem/am?

<b>Odpowiedź:</b>

Tak, nawet osoby, które zalogują się do materiałów 29 kwietnia i tego dnia rozwiążą 15 zadań otrzymają dyplom.

