---
title: "Working with the R Program / What’s Next?"
output:
  html_document:
    toc: yes
---

The course, which you have just completed, is a smooth introduction to the R program. Now, you can read and process the data, and retrieve information on the additional functions of the R.

The R program offers much more than we have already outlined in this simple course.

In this Episode, we will write where to look for further information on the R capabilities.

And to test your skills, we encourage you to take a part in a game, which consists in accomplishing 20 tasks related to the R. In order to complete the course, you need to do any 11 exercises. The persons, who will succeed to accomplish 16 tasks, will additionally be awarded with a mug (the offer valid while the mugs are still available). The list of these 20 exercises is presented in the next Episode.

## Books

### In Polish

Coraz więcej książek, podręczników i artykułów jest poświęconych programowi R.

W pierwszej kolejności chciałbym polecić pozycję, którą sam przygotowałem będąc doktorantem. 
Co jakiś czas ją uaktualniam, do dziś doczekała się ona trzeciego rozszerzonego wydania. 
Można z jej pomocą poznać podstawy języka R jak również bardziej zaawansowane mechanizmy takie jak pakiet *knitr* do automatycznego tworzenia raportów, funkcje do analizy danych, prezentowania danych, optymalizacji, przetwarzania wielkoskalowego oraz wiele innych tematów (omówionych jest ponad 500 funkcji dostępnych w R). Połowa tej książki dostępna jest bezpłatnie na poniższej stronie.

More and more books, manuals, and articles cover the R program issues.

First of all, I would like to recommend a reference title, which I developed myself when I was a doctoral student. Since then I have been updating it, so now it is its third revised release. You can use it to learn both the R language and more advanced solutions, such knitr package to automatically create the reports, the functions of data analysis, presentation, optimisation, large-scale processing, and many other topics (more than 500 functions available in the R are discussed). A half of this book is available free of charge on this website.

> *Przewodnik po pakiecie R* *Przemysław Biecek*   
> http://biecek.pl/R/

One of the first reference titles, which cover the R language in Polish language, is the book by Łukasz Komsta available free of charge at:

> *Wprowadzenie do środowiska R* *Łukasz Komsta* 
> http://cran.r-project.org/doc/contrib/

Today, there are many books in Polish written by the authors that put an emphasis on the language, the applications (whether in biology, economics, or other fields), or the specified methods (analysis of spatial data, time series, or regression analysis).

> The full list of the Polish books is developed on the Wikipedia at  
> http://pl.wikipedia.org/wiki/R_(j%C4%99zyk_programowania)#Polskie_ksi.C4.85.C5.BCki_o_R

### In English

There are a lot of good and bad reference titles in English.

For those more interested in the language, I especially recommend the open book

> *Advanced R* *Hadley Wickham*   
> http://adv-r.had.co.nz/   

You can find the list of more than 150 other books on the R at

> http://www.r-project.org/doc/bib/R-books.html

In English, there are also the online courses on the R available at such websites as

> https://www.coursera.org/ or https://www.edx.org/

## For Excel users

For the Excel users who would like to move seamlessly from Excel to R, I recommend a great book available in whole online and developed by John Taveras ,,R for Excel Users''.

The book is driven by an eye-pleasing motto “Excel analysts who know R can do more with data”.

> http://www.rforexcelusers.com/book/preface/

In addition, the blog by Marco Ghislanzoni, where many video materials, which show how some Excel operations, can be performed in the R, is available at

> http://marcoghislanzoni.com/blog/

## Blogs

### In Polish

In Polish, we can read about the R at

> http://smarterpoland.pl/index.php/category/r/  
> http://thinking-in-r.blogspot.com/  

### In English

The collection of many interesting blogs about the R can be found at

> http://www.r-bloggers.com/

## Meetings of the R users

### In Poland

SER – Warsaw

> http://smarterpoland.pl/SER

PAZUR – Poznań

> http://estymator.ue.poznan.pl/pazur/

eRka – Cracow

> http://www.erkakrakow.pl/

WZUR – Wrocław (it has been suspended for some time, but who knows...)

> http://www.biecek.pl/WZUR/

### Worldwide

The list of many R user groups worldwide is available at:

> http://blog.revolutionanalytics.com/local-r-groups.html
