---
title: "Co dalej?"
author: "pogRomcy danych"
date: "sezon 1 / odcinek 27 <br><br> Wszelkie prawa zastrzeżone.<br> Wykorzystanie możliwe wyłącznie za zgodą autora.  <br><br><br><br>Naciśnij `A` by zamienić slajdy na ciągły tekst. <br> Naciśnij `T` by wyświetlić spis treści."
output:
  slidy_presentation:
    includes:
      in_header: ../tracking.html
    highlight: default
    css: ../style.css
    font_adjustment: 0
    footer: "pogRomcy danych / co dalej / co dalej"

---

Kurs, który właśnie Państwo ukończyli jest łagodnym wprowadzeniem do programu R. 
Potrafią Państwo teraz wczytać i przetwarzać dane oraz szukać informacji o dodatkowych funkcjonalnościach R.

Program R ma do zaoferowania znacznie więcej, niż zdążyliśmy zaznaczyć w tym prostym kursie.

W tym odcinku napiszemy gdzie szukać dalszych informacji o możliwościach R.

A aby sprawdzić swoje umiejętności zapraszamy do wzięcia udziału w zabawie w rozwiązanie 20 zadań związanych z R.
Rozwiązanie dowolnych 11 zadań jest wymagane do zaliczenia kursu. Osoby, którym uda się rozwiązać 16 zadań, dostaną dodatkowo kubek (oferta ważna do wyczerpania kubków). 
Lista tych 20 zadań znajduje się w kolejnym odcinku.


## Książki

### W języku polskim

Coraz więcej książek, podręczników i artykułów jest poświęconych programowi R.

W pierwszej kolejności chciałbym polecić pozycję, którą sam przygotowałem będąc doktorantem. 
Co jakiś czas ją uaktualniam, do dziś doczekała się ona trzeciego rozszerzonego wydania. 
Można z jej pomocą poznać podstawy języka R jak również bardziej zaawansowane mechanizmy takie jak pakiet *knitr* do automatycznego tworzenia raportów, funkcje do analizy danych, prezentowania danych, optymalizacji, przetwarzania wielkoskalowego oraz wiele innych tematów (omówionych jest ponad 500 funkcji dostępnych w R). Połowa tej książki dostępna jest bezpłatnie na poniższej stronie.

> *Przewodnik po pakiecie R* *Przemysław Biecek*   
> http://biecek.pl/R/

Jedna z pierwszych pozycji poświęconych językowi R w języku polskim, do dziś dostępna bezpłatnie, to książka Łukasza Komsty dostępna pod adresem

> *Wprowadzenie do środowiska R* *Łukasz Komsta* 
> http://cran.r-project.org/doc/contrib/

Dziś w języku polskim jest wiele książek, pisanych przez autorów kładących nacisk na język, na zastosowania (czy to w biologii, ekonomii, czy innych dziedzinach) oraz na określone metody (analiza danych przestrzennych, szeregów czasowych, analiza regresyjna).

> Pełna lista polskich książek jest rozwijana na stronie Wikipedii   
> http://pl.wikipedia.org/wiki/R_(j%C4%99zyk_programowania)#Polskie_ksi.C4.85.C5.BCki_o_R

### W języku angielskim 

W języku angielskim występuje zatrzęsienie dobrych i słabych pozycji.

Dla osób zainteresowanych głębiej językiem szczególnie polecam otwartą książkę   

> *Advanced R* *Hadley Wickham*   
> http://adv-r.had.co.nz/   

Lista ponad 150 innych książek o R znajduje się na stronie   

> http://www.r-project.org/doc/bib/R-books.html

W języku angielskim są również dostępne kursy online dotyczące R na takich serwisach jak   

> https://www.coursera.org/ czy https://www.edx.org/

## Dla użytkowników Excela

Użytkownikom Execela, którzy chcieliby przejść płynnie z Excela do R polecam świetną książkę,
dostępną w całości online opracowaną przez Johna Taverasa ,,R for Excel Users''.

Książce przyświeca miłe dla oka motto ,,Excel analysts who know R can do more with data''.

http://www.rforexcelusers.com/book/preface/


Oraz blog prowadzony przez Marco Ghislanzoni na którym dostępnych jest wiele materiałów video porównujących jak pewne ,,Excelowe'' rzeczy można zrobić w R.

http://marcoghislanzoni.com/blog/



## Blogi

### W języku polskim
W języku polskim o R można poczytać na stronach 

> http://smarterpoland.pl/index.php/category/r/  
> http://thinking-in-r.blogspot.com/  

### W języku angielskim
Agregator wielu ciekawych blogów poświęconych R znajduje się na stronie  

> http://www.r-bloggers.com/

## Spotkania użytkowników R

### W Polsce 

SER - Warszawa  

> http://smarterpoland.pl/SER

PAZUR - Poznań  

> http://estymator.ue.poznan.pl/pazur/

eRka - Kraków  

> http://www.erkakrakow.pl/

WZUR - Wrocław (już od jakiegoś czasu wstrzymany, ale kto wie)  

> http://www.biecek.pl/WZUR/

### Na świecie

Lista wielu grup użytkowników R na całym świecie:   

> http://blog.revolutionanalytics.com/local-r-groups.html


