# 0 = echo=FALSE, results="hide", eval=FALSE
use_code=1
knitr_error=FALSE

files:=00_credits 01_interaktywnaPracaZR 02_introR 03_instalacja 04_wprowadzenieDoRStudio 05_wczytywanie 06_zapisywanie 07_indeksowanie 08_petle 09_instrukcje_warunkowe 10_funkcje 11_ilosciowe 12_jakosciowe 13_logiczne 14_napisowe 15_daty 16_dplyrIntro 17_dplyr_filter 18_dplyr_sort 19_dplyr_potok 20_dplyr_select 21_dplyr_mutate 22_dplyr_summarise 23_dplyr_groupby 24_tidyr 77_przypadekUzycia 99_coDalej

include ../Makefile
