---
title: "Challange"
author: "pogRomcy danych"
date: "sezon 0 / odcinek 0 <br><br> Wszelkie prawa zastrzeżone.<br> Wykorzystanie możliwe wyłącznie za zgodą autora.  <br><br><br><br>Naciśnij `A` by zamienić slajdy na ciągły tekst. <br> Naciśnij `T` by wyświetlić spis treści."
output:
  slidy_presentation:
    includes:
      in_header: ../tracking.html
    highlight: default
    css: ../style.css
    font_adjustment: 0
    footer: "pogRomcy danych / challange / sezon 1 "
---

# Zadanie, sezon 1, odcinek 1

Pod adresem `http://biecek.pl/R/dane/daneO.csv` znajduje się zbiór danych, w którego pierwszej kolumnie znajduje się zmienna `Wiek`. Policz średnią wartość z tej kolumny i przypisz do zmiennej `srWiek`.

Przykładowe rozwiązanie:

```{r}

dat <- read.table("http://biecek.pl/R/dane/daneO.csv", sep=";")
srWiek <- mean(dat$Wiek)

```

Test


```{r}

isCorrect <- ifelse(abs(srWiek - 45.5154) < 0.001, TRUE, FALSE)
comments <- ifelse(abs(srWiek - 45.5154) < 0.001, "", "To nie jest poprawna odpowiedź")

```


